version: '3'

services:
  web:
    build: ./docker/web
    volumes:
      - ./web:/var/www/html
    ports:
      - 8080:80
    links:
      - database
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/_data/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
